### ISSUE TITLE
Extend the `matrix.yaml` specification to allow specifying environment variables per container

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/devcontainers#97]
Currently, the containers that are built and published are specified in the `matrix.yaml` file and follow a format like:
```
- os: "ubuntu:18.04"
  images:
  - features: [*gcc_6, *cuda_prev_min, *python, *lit]
  - features: [*gcc_7, *cuda_prev_min, *python, *lit]
  - features: [*gcc_8, *cuda_prev_min, *python, *lit]
  - features: [*gcc_9, *cuda_prev_min, *python, *lit]
  - features: [*llvm_9, *cuda_prev_min, *python, *lit]
  - features: [*oneapi_2022, *cuda_prev_min, *python, *lit]
 ```

Where we specify the base OS container and then a list of features to install in each generated image. 

I would like to extend this to add the ability to specify custom environment variable definitions in each container environment as well. 

I imagine we could do this by adding an `env` field like this:

```
- os: "ubuntu:18.04"
  images:
  - features: [*gcc_6, *cuda_prev_min, *python, *lit]
    env: {my_var: "my_value"}
```

This would then translate down into the generated `devcontainer.json` as:
```
"containerEnv": {
  "my_var": "my_value"
}
```
